FROM php:7.3-fpm-alpine

MAINTAINER Jam <810441377@qq.com>

RUN apk update \
  && apk add --no-cache \
  tzdata curl \
  libmemcached-dev \
  postgresql-dev \
  freetype-dev \
  libjpeg-turbo-dev \
  libpng-dev

RUN docker-php-ext-install bcmath pcntl pdo_mysql pdo_pgsql mysqli opcache \
  && docker-php-ext-configure gd \
    --with-jpeg-dir=/usr/lib \
    --with-freetype-dir=/usr/include/freetype2 \
  && docker-php-ext-install gd \
  # EXT ZipArchive
  && apk add --no-cache libzip-dev \
  && apk add --virtual .build-deps autoconf g++ make tar \
  && docker-php-ext-configure zip --with-libzip \
  && docker-php-ext-install zip \
  # EXT Redis
  && printf "\n" | pecl install -o -f redis \
  && docker-php-ext-enable redis \
  # EXT Memcached
  && curl -L -o /tmp/memcached.tar.gz "https://github.com/php-memcached-dev/php-memcached/archive/php7.tar.gz" \
  && mkdir -p memcached \
  && tar -C memcached -zxvf /tmp/memcached.tar.gz --strip 1 \
  && cd memcached && phpize && ./configure && make -j$(nproc) && make install \
  && rm -rf memcached \
  && rm /tmp/memcached.tar.gz \
  && docker-php-ext-enable memcached \
  # EXT ImageMagick
  && apk add imagemagick-dev imagemagick \
  && pecl install imagick \
  && docker-php-ext-enable imagick \
  && apk del .build-deps autoconf g++ make openssl-dev \
  && rm -rf /tmp/pear \
  && rm -rf /var/cache/apk/*
